# Generated by Django 5.2.3 on 2025-06-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_image', models.ImageField(upload_to='doctors/')),
                ('doc_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.department')),
            ],
        ),
    ]
