# Generated by Django 5.2.3 on 2025-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_name', models.CharField(max_length=30)),
                ('th_des', models.CharField(max_length=200)),
            ],
        ),
    ]
