# Generated by Django 5.2.3 on 2025-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='th_img',
            field=models.ImageField(blank=True, null=True, upload_to='Therapy/'),
        ),
    ]
