# Generated by Django 5.2.3 on 2025-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='b_button',
        ),
        migrations.AlterField(
            model_name='blog',
            name='b_comment',
            field=models.TextField(max_length=200),
        ),
    ]
