# Generated by Django 5.2.3 on 2025-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_blog_b_button_alter_blog_b_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='b_button',
            field=models.CharField(default='Read More', max_length=100),
        ),
    ]
