# Generated by Django 5.2.3 on 2025-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_blog_b_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='b_con',
            field=models.TextField(default='ok', max_length=2500),
        ),
    ]
