# Generated by Django 5.2.3 on 2025-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_appointment_doctor_appointment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('project', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
