# Generated by Django 5.2.3 on 2025-06-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('d_image', models.ImageField(upload_to='doctors/')),
                ('d_description', models.TextField()),
                ('d_age', models.IntegerField()),
                ('d_experience', models.IntegerField()),
                ('d_qualification', models.CharField(max_length=200)),
                ('d_profsummary', models.TextField()),
                ('d_email', models.EmailField(max_length=254)),
                ('d_phone', models.CharField(max_length=15)),
                ('d_languages', models.CharField(max_length=200)),
                ('d_education', models.TextField()),
                ('d_awards', models.TextField()),
                ('d_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.department')),
            ],
        ),
    ]
