# Generated by Django 5.2.3 on 2025-06-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_doctordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.doctordetails'),
        ),
    ]
